version: '3'
services:
  app:
    build: .
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./:/invest
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5001:5000"
    expose:
      - "80"
    container_name: invest

